# Generated by Django 4.2.21 on 2025-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы ',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Введите номер стола', verbose_name='номер стола')),
                ('sitting', models.PositiveIntegerField(help_text='Введите сколько мест у стола', verbose_name='мест у стола')),
                ('content', models.TextField(help_text='Введите содержимое', verbose_name='содержимое')),
                ('price', models.CharField(default=3000, help_text='Введите цену', max_length=100, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузити фотографию', null=True, upload_to='table_image/photo', verbose_name='фото')),
                ('table_occupiers', models.BooleanField(default=False, verbose_name='занятость стола')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'стол',
                'verbose_name_plural': 'столы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TimeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
