# Generated by Django 4.2.21 on 2025-05-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3000.0, help_text='Введите цену', max_digits=10, verbose_name='Цена'),
        ),
    ]
